- name: install and run nginx
  hosts: web
  become: yes # equal to -b in adhoc commands, getting root access
  tasks:
  - name: install nginx
    ansible.builtin.dnf: #this is used to install packages from anisble
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service: ##this is used to run the service from anisble
      name: nginx
      state: started
      enabled: yes



#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html