- name: variables from files
  hosts: localhost
  vars_files: #variables is calling from different file and have to put the variable file
  - vars.yaml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."


# Output:

# [ ec2-user@ip-172-31-22-153 ~/learn-ansible ]$ ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=urpassword 06-variables-from-files.yml 

# PLAY [variables from files] *******************************************************************************************************************************************************************

# TASK [Gathering Facts] ************************************************************************************************************************************************************************
# ok: [localhost]

# TASK [print override information] *************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "Hi, We are learning DevOps with AWS from Trainer Mohan, Duration is 3.5 Months."
# }

# PLAY RECAP ************************************************************************************************************************************************************************************
# localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   