- name: variables from inventory 
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}. Timings are: {{timings}}"

# Output: 
# [ ec2-user@ip-172-31-22-153 ~/learn-ansible ]$ ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=urpassword 08-variables-inventory.yml 
# [WARNING]:  * Failed to parse /home/ec2-user/learn-ansible/inventory.ini with ini plugin: /home/ec2-user/learn-ansible/inventory.ini:35: Section [all:children] includes undefined group:
# database
# [WARNING]: Unable to parse /home/ec2-user/learn-ansible/inventory.ini as an inventory source
# [WARNING]: No inventory was parsed, only implicit localhost is available

# PLAY [variables from inventory] ***************************************************************************************************************************************************************

# TASK [Gathering Facts] ************************************************************************************************************************************************************************
# ok: [localhost]

# TASK [print information] **********************************************************************************************************************************************************************
# ok: [localhost] => {
#     "msg": "Hi, We are learning DevOps with AWS from Trainer Mohan, Duration is 120hrs. Timings are: 07:15AM IST"
# }

# PLAY RECAP ************************************************************************************************************************************************************************************
# localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   