- name: variables from arguments
  hosts: localhost
  tasks:
  - name: get from args
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"

#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html