# DataTypes:
# int
# float 
# double 
# boolean 
# array 
# arraylist 
# map

# In ansible: 
# number 
# string 
# list 
# map

- name: data types
  hosts: localhost
  vars:
    Course: DevOps with AWS #string
    Tools: # list --> start with "-" is list
    - Linux
    - Shell
    - Ansible
    Experience: # map or dictionary
      DevOps: 3 # number
      AWS: 2
      Docker: 1
    RealProject: true #boolean (true or false)
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"