#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html

- name: demo on loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}} " #lookinto output-1
    loop:
    - linux
    - shell
    - ansible

# Output-1:

#   [ ec2-user@ip-172-31-22-153 ~/learn-ansible ]$ ansible-playbook 15-loops.yaml
#   [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

#   PLAY [demo on loops] **************************************************************************************************************************************************************************

#   TASK [Gathering Facts] ************************************************************************************************************************************************************************
#   ok: [localhost]

#   TASK [print names] ****************************************************************************************************************************************************************************
#   ok: [localhost] => (item=linux) => {
#       "msg": "Hello linux "
#   }
#   ok: [localhost] => (item=shell) => {
#       "msg": "Hello shell "
#   }
#   ok: [localhost] => (item=ansible) => {
#       "msg": "Hello ansible "
#   }

#   PLAY RECAP ************************************************************************************************************************************************************************************
#   localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 