- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}" #by using the keyword item and installing packages
      state: latest
    loop:
    - mysql
    - nginx
    - postfix